export enum StudentAssessmentPerformStatus {
  BEFORE_START = 'BEFORE_START',
  IN_PROGRESS = 'IN_PROGRESS',
  FINISHED = 'FINISHED',
  FINISHED_WITHOUT_PARTICIPATION = 'FINISHED_WITHOUT_PARTICIPATION',
}
